// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvyxoA2YVc24bI8txI9GN9yTszjhItiAI',
    appId: '1:943942649045:web:a77bb67a64b99fb97a0e5c',
    messagingSenderId: '943942649045',
    projectId: 'expense-tracker-app-c8141',
    authDomain: 'expense-tracker-app-c8141.firebaseapp.com',
    storageBucket: 'expense-tracker-app-c8141.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz38K1mc6mpb9yajRkXdY3ixGYdV_YN1Q',
    appId: '1:943942649045:android:6384727cbb7c45377a0e5c',
    messagingSenderId: '943942649045',
    projectId: 'expense-tracker-app-c8141',
    storageBucket: 'expense-tracker-app-c8141.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLIJp3Gtr4rofnSnIjCGOH1UU-EW4AtV4',
    appId: '1:943942649045:ios:96c7192e17b11dc37a0e5c',
    messagingSenderId: '943942649045',
    projectId: 'expense-tracker-app-c8141',
    storageBucket: 'expense-tracker-app-c8141.firebasestorage.app',
    iosBundleId: 'com.example.tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLIJp3Gtr4rofnSnIjCGOH1UU-EW4AtV4',
    appId: '1:943942649045:ios:96c7192e17b11dc37a0e5c',
    messagingSenderId: '943942649045',
    projectId: 'expense-tracker-app-c8141',
    storageBucket: 'expense-tracker-app-c8141.firebasestorage.app',
    iosBundleId: 'com.example.tracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvyxoA2YVc24bI8txI9GN9yTszjhItiAI',
    appId: '1:943942649045:web:be9336796e97ce767a0e5c',
    messagingSenderId: '943942649045',
    projectId: 'expense-tracker-app-c8141',
    authDomain: 'expense-tracker-app-c8141.firebaseapp.com',
    storageBucket: 'expense-tracker-app-c8141.firebasestorage.app',
  );
}
